version: "3.8"

services:

  phpfpm:
    image: larsvandersangen/homebase-backend:dev-latest
    platform: linux/amd64
    build:
      context: .
      target: dev
      dockerfile: ./Dockerfile.dev
    networks:
      - app-network
    environment:
      SERVICE_NAME: phpfpm
      SERVICE_TAGS: dev
    volumes:
      - ./:/var/www/homebase-backend
      - ./docker/config/php.ini:/usr/local/etc/php/conf.d/php.ini
    expose:
      - "9000"
      - "9003"

  # Nginx Service
  nginx:
    image: nginx:alpine
    depends_on:
      - phpfpm
    ports:
      - 8101:8080
    volumes:
      - ./public:/var/www/homebase-backend/public
      - ./docker/config/default.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

  frontend:
    image: larsvandersangen/homebase-frontend:dev-latest
    platform: linux/amd64
    build:
      dockerfile: "${HOMEBASE_FRONTEND_PROJECT_DOCKER_DEV_FILE}"
      context: "${HOMEBASE_FRONTEND_PROJECT_FOLDER}"
    ports:
      - "4200:4200"
    volumes:
      - "${HOMEBASE_FRONTEND_PROJECT_FOLDER}:/usr/src/app"
      - ~/.gitconfig:/etc/gitconfig
    environment:
      SHELL: /bin/bash
      NODE_ENV: development
    networks:
      - app-network
    entrypoint: ng serve --host 0.0.0.0 --configuration=development
    env_file:
      - .env

  redis:
    image: "redis:latest"


  ###> doctrine/doctrine-bundle ###
  database:
    image: mysql:8.0.33
    networks:
      - app-network
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: homebase-dev
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - database_data:/var/lib/mysql
    ports:
      - "3306:3306"
      - "33060:33060"
    expose:
      - 3306
      - 33060
  ###< doctrine/doctrine-bundle ###

# Docker Networks
networks:
  app-network:
    name: app-network
    driver: bridge


volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
