version: "3.8"

services:

  phpfpm:
    build:
      context: .
      target: dev
      dockerfile: ./Dockerfile.dev
    networks:
      - app-network
#    depends_on:
#      - backend-sqs
#      - backend-redis
    environment:
      SERVICE_NAME: phpfpm
      SERVICE_TAGS: dev
    volumes:
#      - ./docker/config/fpm-pool.conf:/etc/php7/php-fpm.d/www.conf
#      - ./docker/config/php.ini:/usr/local/etc/php/conf.d/custom.ini
#      - ./docker/config/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      - ./:/var/www/homebase-backend
    expose:
      - "9000"
      - "9003"


#
#  db:
#    image: mysql
#    volumes:
#      - /app/node_modules
#      - ./worker:/app
#    environment:
#      - REDIS_HOST=redis
#      - REDIS_PORT=6379


  # Nginx Service
  nginx:
    image: nginx:alpine
    depends_on:
      - phpfpm
    ports:
      - 8101:8080
    volumes:
      - ./public:/var/www/homebase-backend/public
      - ./docker/config/default.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

  frontend:
    build:
      dockerfile: "${HOMEBASE_FRONTEND_PROJECT_FOLDER}/${HOMEBASE_FRONTEND_PROJECT_DOCKER_FILE}"
      context: "${HOMEBASE_FRONTEND_PROJECT_FOLDER}"
    ports:
      - "4200:4200"
    environment:
      SHELL: /bin/bash
      NODE_ENV: development
    volumes:
      - "${HOMEBASE_FRONTEND_PROJECT_FOLDER}:/usr/src/app"
      - ~/.gitconfig:/etc/gitconfig
    entrypoint: ng serve --host 0.0.0.0 --poll 1


  redis:
    image: "redis:latest"

# Docker Networks
networks:
  app-network:
    name: app-network
    driver: bridge
