version: "3.8"

services:

  phpfpm:
    image: larsvandersangen/homebase-backend
    platform: linux/amd64
    build:
      context: .
      target: dev
      dockerfile: ./Dockerfile
    networks:
      - app-network
    environment:
      SERVICE_NAME: phpfpm
      SERVICE_TAGS: dev
    expose:
      - "9000"


  # Nginx Service
  nginx:
    image: nginx:alpine
    depends_on:
      - phpfpm
    ports:
      - 8101:8080
    volumes:
      - ./public:/var/www/homebase-backend/public
      - ./docker/config/default.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

  frontend:
    platform: linux/amd64
    build:
      dockerfile: "${HOMEBASE_FRONTEND_PROJECT_DOCKER_FILE}"
      context: "${HOMEBASE_FRONTEND_PROJECT_FOLDER}"
    image: larsvandersangen/homebase-frontend
    ports:
      - "4200:4200"
    environment:
      SHELL: /bin/bash
      NODE_ENV: development
    entrypoint: ng serve --host 0.0.0.0 --poll 1


  redis:
    image: "redis:latest"

# Docker Networks
networks:
  app-network:
    name: app-network
    driver: bridge
