version: "3.8"

services:

  phpfpm:
    image: larsvandersangen/homebase-backend:dev-latest
    platform: linux/amd64
    build:
      context: .
      target: dev
      dockerfile: ./Dockerfile.dev
    networks:
      - app-network
    environment:
      SERVICE_NAME: phpfpm
      SERVICE_TAGS: dev
    volumes:
      - ./:/var/www/homebase-backend
    expose:
      - "9000"
      - "9003"

  # Nginx Service
  nginx:
    image: nginx:alpine
    depends_on:
      - phpfpm
    ports:
      - 8101:8080
    volumes:
      - ./public:/var/www/homebase-backend/public
      - ./docker/config/default.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

  frontend:
    image: larsvandersangen/homebase-frontend:dev-latest
    platform: linux/amd64
    build:
      dockerfile: "${HOMEBASE_FRONTEND_PROJECT_DOCKER_DEV_FILE}"
      context: "${HOMEBASE_FRONTEND_PROJECT_FOLDER}"
    ports:
      - "4200:4200"
    volumes:
      - "${HOMEBASE_FRONTEND_PROJECT_FOLDER}:/usr/src/app"
      - ~/.gitconfig:/etc/gitconfig
    environment:
      SHELL: /bin/bash
      NODE_ENV: development
    networks:
      - app-network-frontend
    entrypoint: ng serve --host 0.0.0.0 --configuration=development
    env_file:
      - .env

  redis:
    image: "redis:latest"

# Docker Networks
networks:
  app-network:
    name: app-network
    driver: bridge
