version: "3.8"

services:

  phpfpm:
    image: larsvandersangen/homebase-backend
    platform: linux/amd64
    depends_on:
      database:
        condition: service_completed_successfully
    build:
      context: .
      target: dev
      dockerfile: ./Dockerfile
    networks:
      - app-network
    environment:
      SERVICE_NAME: phpfpm
      SERVICE_TAGS: dev
    expose:
      - "9000"

  # Nginx Service
  nginx:
    image: nginx:alpine
    depends_on:
      - phpfpm
    ports:
      - 8101:8080
    volumes:
      - ./public:/var/www/homebase-backend/public
      - ./docker/config/default.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

  frontend:
    image: larsvandersangen/homebase-frontend
    platform: linux/amd64
    build:
      dockerfile: "${HOMEBASE_FRONTEND_PROJECT_DOCKER_FILE}"
      context: "${HOMEBASE_FRONTEND_PROJECT_FOLDER}"
    ports:
      - "4200:4200"
    environment:
      SHELL: /bin/bash
      NODE_ENV: development
    entrypoint: ng serve --host 0.0.0.0 --poll 1


  ###> doctrine/doctrine-bundle ###
  database:
    image: mysql:8.0.33
    networks:
      - app-network
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: homebase-dev
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - database_data:/var/lib/mysql
    ports:
      - "3306:3306"
      - "33060:33060"
    expose:
      - 3306
      - 33060
  ###< doctrine/doctrine-bundle ###

  redis:
    image: "redis:latest"
    networks:
      - app-network

# Docker Networks

networks:
  app-network:
    name: app-network
    driver: bridge


volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
