apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap-defaultconf
  labels:
    folder: homebase-backend-phpfpm
data:
  homebase-backend.conf: |
    
    # Default server definition
    server {
        error_log  /var/log/nginx/error.log;
        access_log /var/log/nginx/access.log;

        listen 80 default_server;
        server_name _;
        fastcgi_param SERVER_NAME $host;

        root /var/www/html/public;
        index index.php index.html;

        location / {
            # First attempt to serve request as file, then
            # as directory, then fall back to index.php
            try_files $uri $uri/ /index.php?q=$uri&$args;

            add_header 'Access-Control-Allow-Origin' '*' always;
        }

        # Redirect server error pages to the static page /50x.html
        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
            root /var/lib/nginx/html;
        }

        # Pass the PHP scripts to PHP-FPM listening on homebase-backend-cluster-ip-phpfpm:9000
        location ~ \.php$ {
            try_files $uri =404;
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass homebase-backend-cluster-ip-phpfpm:9000;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param SCRIPT_NAME $fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
            fastcgi_index index.php;
            include fastcgi_params;

            add_header 'Access-Control-Allow-Origin' '*' always;
        }

        location ~* \.(jpg|jpeg|gif|png|css|js|ico|xml|webp)$ {
            expires 5d;
        }

        # Deny access to . files, for security
        location ~ /\. {
            log_not_found off;
            deny all;
        }

        # Allow fpm ping and status from localhost
        location ~ ^/(fpm-status|fpm-ping)$ {
            access_log off;
            allow 127.0.0.1;
            deny all;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;
            fastcgi_pass homebase-backend-cluster-ip-phpfpm:9000;
        }
    }
