apiVersion: v1
kind: Service
metadata:
  name: homebase-backend-cluster-ip-phpfpm
spec:
  type: ClusterIP
  # ServerClusterIp is coupled to the selector (metadata) tags.
  # Which are entirely customizable.
  selector:
    folder: homebase-backend-phpfpm
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      name: phpfpm
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http