name: Build, test and push - prod

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

#      - name: Cache Composer packages
#        id: composer-cache
#        uses: actions/cache@v3
#        with:
#          path: vendor
#          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
#          restore-keys: |
#            ${{ runner.os }}-php-

      - name: Setup and test
        run: |
          touch .env.local
          echo APP_ENV=$APP_ENV >> .env.local
          
          make up-database-test
          make up-phpfpm-test
          make test
        env:
          APP_ENV: prod

      - name: Prepare artifact
        run: |
          echo DATABASE_URL=$DATABASE_URL_PROD >> .env.local
          echo REDIS_URL=$REDIS_URL >> .env.local

          make up-phpfpm
        env:
          APP_ENV: prod
          DATABASE_URL_PROD: ${{secrets.DATABASE_URL_PROD}}
          REDIS_URL: ${{secrets.REDIS_URL}}

      - name: Docker compose push
        run: |
          docker login -u ${{ vars.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          make docker-push-phpfpm

      - name: kubectl-set
        uses: qgxpagamentos/kubectl-set@v1
        with:
          # A base64 encoded reference to your authorization file (~/.kube/config)
          base64-kube-config: ${{ secrets.K8S_KUBE_CONFIG }}


      - name: Deploy to k8s
        run: |
          make k8s-deploy-prod
        env:
          K8S_NAMESPACE: ${{secrets.K8S_PROD_NAMESPACE}}
