apiVersion: v1
kind: Service
metadata:
  name: homebase-backend-redis-cluster-ip
spec:
  type: ClusterIP
  selector:
    folder: redis-test
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
      name: redis